### ISSUE TITLE
Support proper JSON formatted logs

### ISSUE THREAD

**Issue by xissy** [daangn/accesslog#22]
I am wondering if we could have more proper JSON formatted logs like TO-BEs. It would be great since it can be parsed and indexed well on log index engines such as elasticsearch.

AS-IS
`{"protocol":"http","path":"/ping","status":"200","ua":"curl/7.64.1","time":"2021-12-09T02:39:46.026696Z","elapsed(ms)":0.033,"data":"{\"foo\": \"bar\"}"}
`

TO-BE 1
`{"protocol":"http","path":"/ping","status":"200","ua":"curl/7.64.1","time":"2021-12-09T02:39:46.026696Z","elapsed(ms)":0.033,"data":{"foo": "bar"}}`

TO-BE 2
`{"protocol":"http","path":"/ping","status":"200","ua":"curl/7.64.1","time":"2021-12-09T02:39:46.026696Z","elapsed(ms)":0.033,"data.foo":"bar"}`

**Comment by zzerjae** [comment]
[the example](https://github.com/daangn/accesslog/blob/main/examples/stdout/main.go#L19) in README is just an example output when [Bytes()](https://github.com/rs/zerolog/blob/master/event.go#L288-L298) is used. You can get JSON formatted logs by utilizing [Interface()](https://github.com/rs/zerolog/blob/master/event.go#L710-L720) like this:

```go
package main

import (
	"net/http"

	"github.com/daangn/accesslog"
	"github.com/daangn/accesslog/middleware"
	"github.com/go-chi/chi/v5"
	"github.com/rs/zerolog"
)

type Foo struct {
	Foo string `json:"foo"`
}

func main() {
	r := chi.NewRouter()
	r.Use(middleware.AccessLog(accesslog.DefaultHTTPLogger))
	r.Get("/ping", func(w http.ResponseWriter, r *http.Request) {
		accesslog.GetLogEntry(r.Context()).Add(func(e *zerolog.Event) {
			e.Interface("data", Foo{Foo: "bar"})
		})
		w.Write([]byte("pong"))
	})

	http.ListenAndServe(":3000", r)
}

```
